services:
  healthy-diet-ai-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: healthy-diet-ai-agent
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PORT: 8001
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8001:8001"
    volumes:
      - ./knowledge_base:/app/knowledge_base
      - ./users_images:/app/users_images
